# 04 SQL Database Setup

## Objective

Load the processed housing affordability dataset into a local SQLite database for SQL analysis.

## Input

- `data/processed/housing_macro_with_stress_score.csv`

## Output

- `housing_affordability.db`

## Tables Created

- `housing_macro_country_year`

In [1]:
import pandas as pd
import sqlite3
from pathlib import Path

PROCESSED_DIR = Path("../data/processed")
DB_PATH = Path("../housing_affordability.db")

print("Setup complete")

Setup complete

In [2]:
df = pd.read_csv(PROCESSED_DIR / "housing_macro_with_stress_score.csv")

print("Shape:", df.shape)
df.head()

Shape: (902, 27)

,country_id,country_name,year,nominal_house_price_index,price_to_income_ratio,price_to_rent_ratio,real_house_price_index,rent_price_index,gdp_per_capita_constant_usd,gdp_per_capita_current_usd,...,rent_price_yoy_growth_pct,gdp_per_capita_yoy_growth_pct,house_price_income_gap,price_to_income_ratio_scaled,real_house_price_index_scaled,price_to_rent_ratio_scaled,urban_population_growth_pct_scaled,house_price_income_gap_scaled,housing_affordability_stress_score,housing_stress_category
0,AUS,Australia,2000,33.595673,67.822665,58.062251,47.961090,57.862362,45979.076565,21908.996802,...,NaN,NaN,0.629113,0.076037,0.260003,0.104041,0.456003,0.728783,23.090065,Low
1,AUS,Australia,2001,37.368512,69.777135,62.618848,51.543695,59.662722,46314.623530,19733.651010,...,3.111453,0.729782,6.740034,0.088434,0.279783,0.135394,0.483803,0.772478,25.360450,Low
2,AUS,Australia,2002,44.372389,81.271639,72.558473,59.617939,61.144035,47599.407929,20335.096019,...,2.482811,2.774036,12.890817,0.161339,0.324362,0.203785,0.479150,0.816459,30.787703,Low
3,AUS,Australia,2003,52.375657,91.792473,84.071694,68.972989,62.283510,48509.663218,23757.589847,...,1.863592,1.912325,13.779345,0.228068,0.376013,0.283004,0.479148,0.822812,36.062383,Low
4,AUS,Australia,2004,55.647000,91.233649,87.154344,72.246883,63.855978,50018.590448,30886.050095,...,2.524693,3.110570,1.636061,0.224524,0.394088,0.304215,0.465724,0.735983,35.811907,Low

In [3]:
conn = sqlite3.connect(DB_PATH)

df.to_sql(
    "housing_macro_country_year",
    conn,
    if_exists="replace",
    index=False
)

print("Table loaded successfully")

Table loaded successfully

In [4]:
query = """
SELECT
    country_name,
    year,
    housing_affordability_stress_score,
    housing_stress_category
FROM housing_macro_country_year
ORDER BY housing_affordability_stress_score DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,country_name,year,housing_affordability_stress_score,housing_stress_category
0,Russia,2007,87.890019,Severe
1,Russia,2008,85.263063,Severe
2,Bulgaria,2008,80.814301,Severe
3,Latvia,2007,78.514872,Severe
4,Ireland,2007,78.452767,Severe
5,Ireland,2006,77.970766,Severe
6,Lithuania,2007,76.859966,Severe
7,Luxembourg,2022,76.036022,Severe
8,Portugal,2024,75.350577,Severe
9,Spain,2007,73.953239,High

In [5]:
conn.close()
print("Database connection closed")

Database connection closed